### ISSUE TITLE
add a col_counts between split_cols_by

### ISSUE THREAD

**Issue by huanlusanofi** [Roche/rtables#339] opened 2022-07-11 09:04 UTC
Hi develops, when I was standing on {rtables}'s shoulder and looking at a table:

![image](https://user-images.githubusercontent.com/43463262/178228264-6cccb33e-d031-4001-963c-9942e2668f06.png)

The closest I can reached, which exhausted every drop of blood (unfortunately), is like this:

![image](https://user-images.githubusercontent.com/43463262/178228884-0e8379d7-afa7-49d6-8a64-1cf05c8c3961.png)

My question is that, is there any parameter to control it to have the col_counts calculated on the first level? Many thanks!!!

**Comment by shajoezhu** [comment] 2022-07-11 12:27
hi @huanlusanofi , one way to do this is to during your preprocessing step, modify your treatment arm labels, and add the total count. For example, "TRT A" becomes "TRT A (N = 253)"

**Comment by gmbecker** [comment] 2022-07-11 20:00
@huanlusanofi @shajoezhu is correct. There is currently no way to add column counts levels other than the lowest level of the column structure.

This is primarily due to the fact that we allow column counts to be overridden, and doing so on any level but the lowest (ie last split, most granular) level would require a tree model for specifying them, which I haven't come up with to my satisfaction yet. 

Joe is also correct about the easiest workaround, which is to to modify the labels (note this need not modify the actual values, as labels *can* be different from values for a splitting variable) via preprocessing. 

You could also do it after the fact via manipulation of the *matrix_form* of your table, though that is more of an "advanced usage".

**Comment by huanlusanofi** [comment] 2022-07-12 03:09
> hi @huanlusanofi , one way to do this is to during your preprocessing step, modify your treatment arm labels, and add the total count. For example, "TRT A" becomes "TRT A (N = 253)"

Thank you very much! This is nice!

**Comment by huanlusanofi** [comment] 2022-07-12 03:10
> @huanlusanofi @shajoezhu is correct. There is currently no way to add column counts levels other than the lowest level of the column structure.
> 
> This is primarily due to the fact that we allow column counts to be overridden, and doing so on any level but the lowest (ie last split, most granular) level would require a tree model for specifying them, which I haven't come up with to my satisfaction yet.
> 
> Joe is also correct about the easiest workaround, which is to to modify the labels (note this need not modify the actual values, as labels _can_ be different from values for a splitting variable) via preprocessing.
> 
> You could also do it after the fact via manipulation of the _matrix_form_ of your table, though that is more of an "advanced usage".

Fully understand that, using labels at this stage has no difficulties to meet my need, thank you!

**Comment by gmbecker** [comment] 2022-08-10 00:12
closing as duplicate of #135

**Closed by gmbecker** 2022-08-10 00:12 UTC
