### ISSUE TITLE
Error in `load_all()`

### ISSUE THREAD

**Issue by StefanThoma** [Roche/rtables#436] opened 2022-11-07 20:37 UTC
I am writing (a draft of) a vignette for custom split functions.
When I try to run `devtools::document()` I get the following output:  

```
 Updating rtables documentation
 Loading rtables
Creating a generic function for ‘nrow’ from package ‘base’ in package ‘rtables’
Creating a generic function for ‘ncol’ from package ‘base’ in package ‘rtables’
Error in `load_all()`:
! Failed to load R/tree_accessors.R
Caused by error in `setMethod()`:
! no existing definition for function ‘table_inset’
Run `rlang::last_error()` to see where the error occurred.
```

This happens before I change anything. 
I run this on a vanilla `rstudio` cloud instance with:
```
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3
LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] formatters_0.3.4.4 magrittr_2.0.3    

loaded via a namespace (and not attached):
[1] compiler_4.2.1  fastmap_1.1.0   cli_3.4.1       htmltools_0.5.3 tools_4.2.1    
[6] rstudioapi_0.14 grid_4.2.1      digest_0.6.30   rlang_1.0.6    
```

Thanks for your help!

**Comment by gmbecker** [comment] 2022-11-07 21:20
Looks like rtables is not being loaded for some reason. When I do `devtools::document()` I get:

```
> devtools::document()
ℹ Updating rtables documentation
ℹ Loading rtables
Loading required package: magrittr
Loading required package: formatters
Creating a generic function for ‘nrow’ from package ‘base’ in package ‘rtables’
Creating a generic function for ‘ncol’ from package ‘base’ in package ‘rtables’
Creating a generic function for ‘rbind’ from package ‘base’ in package ‘rtables’
Warning message:
In setup_ns_exports(path, export_all, export_imports) :
  Objects listed as exports, but not present in namespace: [, [<-
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtables_0.5.3.1    formatters_0.3.4.4 magrittr_2.0.3    

loaded via a namespace (and not attached):
 [1] pillar_1.7.0      compiler_4.1.2    prettyunits_1.1.1 remotes_2.4.2    
 [5] tools_4.1.2       digest_0.6.29     testthat_3.1.3    pkgbuild_1.3.1   
 [9] pkgload_1.2.4     memoise_2.0.1     lifecycle_1.0.1   tibble_3.1.8     
[13] pkgconfig_2.0.3   rlang_1.0.6       cli_3.3.0         rstudioapi_0.13  
[17] commonmark_1.8.0  xfun_0.30         fastmap_1.1.0     withr_2.5.0      
[21] stringr_1.4.1     roxygen2_7.2.1    knitr_1.38        xml2_1.3.3       
[25] desc_1.4.1        fs_1.5.2          vctrs_0.4.2       devtools_2.4.3   
[29] grid_4.1.2        rprojroot_2.0.3   glue_1.6.2        R6_2.5.1         
[33] processx_3.5.3    fansi_1.0.3       sessioninfo_1.2.2 callr_3.7.0      
[37] purrr_0.3.5       codetools_0.2-18  htmltools_0.5.2   ps_1.6.0         
[41] ellipsis_0.3.2    usethis_2.1.5     utf8_1.2.2        stringi_1.7.6    
[45] cachem_1.0.6      crayon_1.5.1      brio_1.1.3       
```

That said, I generally avoid `devtools::load_all` because devtools doesn't always do particularly well with S4 (though I am not able to reproduce this particular error you're seeing)

**Comment by Melkiades** [comment] 2022-11-08 10:22
I was not able to reproduce it locally either. What happens if you use: `roxygen2::roxygenize('.', roclets = c('rd', 'collate', 'namespace'))`?

**Comment by Melkiades** [comment] 2022-11-08 15:47
Could you try to do `devtools::load_all()`? Also try `rlang::last_error()` even if I guess it will be more confusing than anything. I would suggest also trying to install it also directly from source (or using `devtools::install_github`)

**Comment by Melkiades** [comment] 2022-11-17 17:02
Closing this for the moment. Please feel free to reopen if this happens again

**Closed by Melkiades** 2022-11-17 17:02 UTC
