### ISSUE TITLE
Indentation of analysis rows under `insert_rrow`

### ISSUE THREAD

**Issue by anajens** [Roche/rtables#202] opened 2021-05-11 13:36 UTC
Currently, when using `insert_rrow` with a label row only the first set of analysis rows are indented. However if a non label row is inserted, all rows below are indented. Is this intentional? 

```r
library(rtables)

tbl <- basic_table() %>%
  analyze("AGE", show_labels = "hidden") %>%
  analyze("SEX", show_labels = "hidden", indent_mod = 1L) %>%
  analyze("BMRKR1", show_labels = "hidden", indent_mod = 1L) %>%
  build_table(ex_adsl)
```

```
> tbl
                     all obs
----------------------------
Mean                  34.88 
  F                    222  
  M                    166  
  U                     9   
  UNDIFFERENTIATED      3   
  Mean                5.76  
> insert_rrow(tbl, rrow("ABC heading"), at = 2)
                       all obs
------------------------------
Mean                    34.88 
  ABC heading                 
    F                    222  
    M                    166  
    U                     9   
    UNDIFFERENTIATED      3   
  Mean                  5.76  
> insert_rrow(tbl, rrow("ABC heading", ""), at = 2)
                     all obs
----------------------------
Mean                  34.88 
ABC heading                 
  F                    222  
  M                    166  
  U                     9   
  UNDIFFERENTIATED      3   
  Mean                5.76  
```

Session info:
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rtables_0.3.7.0005 magrittr_2.0.1    

loaded via a namespace (and not attached):
[1] compiler_3.6.3  htmltools_0.4.0 tools_3.6.3     Rcpp_1.0.4.6    digest_0.6.25   packrat_0.5.0   rlang_0.4.9
```

**Comment by gmbecker** [comment] 2021-07-14 21:08
Hi @anajens

I get why this is confusing, but yes this is expected - and I think, technically correct - behavior.

The issue is, as it often is, is`indent_mod`.  Remember, `indent_mod` modifies the indentation of a structure ***and all its children***. The modification is ***relative to what it would naturally be*** and finally, it occurs ***at printing time***.

Any  time your layout has indent mods and the resulting indentation is confusing, I encourage you to strip all the indent_mods out and look at the results.  I also encourage only using `indent_mod` on tables you won't be structurally altering via post-processing unless it is absolutely necessary. 

Removing the `indent_mod` gives us a better picture of what is happening:

```
tbl <- basic_table() %>%
+   analyze("AGE", show_labels = "hidden") %>%
+   analyze("SEX", show_labels = "hidden") %>%
+   analyze("BMRKR1", show_labels = "hidden") %>%
+   build_table(ex_adsl)
> 
> tbl
                   all obs
--------------------------
Mean                34.88 
F                    222  
M                    166  
U                     9   
UNDIFFERENTIATED      3   
Mean                5.76  
> 
> insert_rrow(tbl, rrow("ABC heading"), at = 2)
                     all obs
----------------------------
Mean                  34.88 
ABC heading                 
  F                    222  
  M                    166  
  U                     9   
  UNDIFFERENTIATED      3   
Mean                  5.76  
> 
> insert_rrow(tbl, rrow("ABC heading", ""), at = 2)
                   all obs
--------------------------
Mean                34.88 
ABC heading               
F                    222  
M                    166  
U                     9   
UNDIFFERENTIATED      3   
Mean                5.76  
```



Now consider what (visible) label rows do. They print a label *and increment the natural indentation for all children*. Inserting a label row (correctly, I believe) tries to find a correctly positioned subtable and adds a visible label row to it. In this case, that is the table representing the analysis of the SEX variable. In your case this is unambiguous, but it could be ambiguous in more complex structures. 

If, on the other hand, we insert a data row, "position 2" is actually ambiguous. The algorithm places it as a sibling directly after row 1 which is a Data row, ie  in the `AGE` analysis subtable, after the Mean row. It *could* have also placed it within `SEX` before `F`, but when we were thinking about this upon first putting it in we felt that it being greedy (ie the first place it can be validly placed when walking the tree, thus always a last sibling rather than a first child in the following subtree)  was a good deterministic rule.

So in *this* case in your original layouts, the indentation of the rows which appear after our inserted row actually have nothing to do with our insertion, they are unchanged and are completely a result of the indent modifiers in play.

Another function that is helpful here is 

`table_structure(., "row")`

Which gives us the very verbose but ultimately quite informative:

```
> table_structure(tbl, "row")
TableTree: [ma_AGE_SEX_BMRKR1] ()
  labelrow: [] () - <not visible>
  children: 
    ElementaryTable: [AGE] (AGE)
      labelrow: [AGE] (AGE) - <not visible>
      children: 
        DataRow: [Mean] (Mean)
    ElementaryTable: [SEX] (SEX)
      labelrow: [SEX] (SEX) - <not visible>
      children: 
        DataRow: [F] (F)
        DataRow: [M] (M)
        DataRow: [U] (U)
        DataRow: [UNDIFFERENTIATED] (UNDIFFERENTIATED)
    ElementaryTable: [BMRKR1] (BMRKR1)
      labelrow: [BMRKR1] (BMRKR1) - <not visible>
      children: 
        DataRow: [Mean] (Mean)
> table_structure(insert_rrow(tbl, rrow("Label"), 2), "row")
TableTree: [ma_AGE_SEX_BMRKR1] ()
  labelrow: [] () - <not visible>
  children: 
    ElementaryTable: [AGE] (AGE)
      labelrow: [AGE] (AGE) - <not visible>
      children: 
        DataRow: [Mean] (Mean)
    ElementaryTable: [SEX] (Label)
      labelrow: [Label] (Label)
      children: 
        DataRow: [F] (F)
        DataRow: [M] (M)
        DataRow: [U] (U)
        DataRow: [UNDIFFERENTIATED] (UNDIFFERENTIATED)
    ElementaryTable: [BMRKR1] (BMRKR1)
      labelrow: [BMRKR1] (BMRKR1) - <not visible>
      children: 
        DataRow: [Mean] (Mean)
> table_structure(insert_rrow(tbl, rrow("data", ""), 2), "row")
TableTree: [ma_AGE_SEX_BMRKR1] ()
  labelrow: [] () - <not visible>
  children: 
    ElementaryTable: [AGE] (AGE)
      labelrow: [AGE] (AGE) - <not visible>
      children: 
        DataRow: [Mean] (Mean)
        DataRow: [data] (data)
    ElementaryTable: [SEX] (SEX)
      labelrow: [SEX] (SEX) - <not visible>
      children: 
        DataRow: [F] (F)
        DataRow: [M] (M)
        DataRow: [U] (U)
        DataRow: [UNDIFFERENTIATED] (UNDIFFERENTIATED)
    ElementaryTable: [BMRKR1] (BMRKR1)
      labelrow: [BMRKR1] (BMRKR1) - <not visible>
      children: 
        DataRow: [Mean] (Mean)
```

Honestly there are some pretty problematic ambiguities in what insert_rrow should do for non-trivial, non-elementary table structures. I'm becoming less convinced we should or even can support it sanely in the fully general case. We'll need to discuss this, but I will start a new issue for that. I'm closing this one as expected/correct behavior.

**Closed by gmbecker** 2021-07-14 21:08 UTC
