### ISSUE TITLE
`head()` doesn't preserve the top left corner created by `append_topleft()`

### ISSUE THREAD

**Issue by wangh107** [Roche/rtables#335] opened 2022-06-23 21:07 UTC
The top left corner information created by `append_topleft()` in rtable disappears when using `head()`. 

```r
library(dplyr)
library(rtables)
lyt <- basic_table() %>%
  split_cols_by("ARM") %>% 
  split_rows_by("RACE") %>%
  append_topleft("Ethnicity") %>%
  analyze("AGE") %>%
  append_topleft("  Age")
 
tbl <- build_table(lyt, DM)

```

```
> tbl

Ethnicity                                                                          
  Age                                       A: Drug X   B: Placebo   C: Combination
———————————————————————————————————————————————————————————————————————————————————
ASIAN                                                                              
  Mean                                        34.20       32.68          34.63     
BLACK OR AFRICAN AMERICAN                                                          
  Mean                                        34.68       31.71          34.00     
WHITE                                                                              
  Mean                                        39.36       36.93          35.11     
AMERICAN INDIAN OR ALASKA NATIVE                                                   
  Mean                                         NA           NA             NA      
MULTIPLE                                                                           
  Mean                                         NA           NA             NA      
NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER                                          
  Mean                                         NA           NA             NA      
OTHER                                                                              
  Mean                                         NA           NA             NA      
UNKNOWN                                                                            
  Mean                                         NA           NA             NA      
```

```
> head(tbl)
                            A: Drug X   B: Placebo   C: Combination
———————————————————————————————————————————————————————————————————
ASIAN                                                              
  Mean                        34.20       32.68          34.63     
BLACK OR AFRICAN AMERICAN                                          
  Mean                        34.68       31.71          34.00     
WHITE                                                              
  Mean                        39.36       36.93          35.11     
```

**Comment by gmbecker** [comment] 2022-06-24 00:14
This is, more or less, by design. What to do with top-left when a table is
subset in row space is something of an open question. Top-left materials
are often, though not always, a semantically meaningful summary of the row
structure . In that common case, the top-left would (or at least easily
could) be incorrect after general row-space subsetting.

Head is simply a convenience wrapper around the `[`. The method for `[` for
TableTrees has an additional `keep_topleft` argument^ (which defaults to
FALSE in practice), which you can use for subsetting that does preserve
topleft.

At a very quick glance, It doesn't look like head is going to pass its
`...` down in the right way, so as of now I don't think `head(t,
keep_topleft = TRUE)` is going to work.

^ it also has related arguments: `keep_titles` for keeping title (and I
think, footer) information, which also defaults to FALSE, and
`reindex_refs` for whether referential footnotes should be renumbered,
which defaults to `TRUE`.

HTH,
~G

**Comment by gmbecker** [comment] 2022-07-26 17:55
This is fixed in the above commit and the minor roxygen2 automation failure is fixed in the latest commit

**Closed by gmbecker** 2022-07-26 17:55 UTC
